export const bookingContent = {
  VI: {
    clientInformation: "Thông tin khách hàng",
    person: "Người",
    fullName: "Tên khách hàng",
    phone: "Số điện thoại",
    fullNamePlaceholder: "Nhập tên khách hàng",
    phonePlaceholder: "Nhập số điện thoại",
    availableDate: "Ngày có sẵn",
    availableDatePlaceholder: "Chọn ngày đi",
    guestSize: "Số lượng khách",
    guestSizePlaceholder: "Chọn số lượng khách",
    bookingNewDate: "Đặt ngày mới",
    bookingNewDatePlaceholder: "Chọn ngày mới",
    bookingRemainSlots: "Số lượng chỗ còn lại",
    bookingRemainSlotsPlaceholder: "Chọn số lượng chỗ còn lại",
    bookingSlots: "Số lượng chỗ",
    bookingSlotsPlaceholder: "Chọn số lượng chỗ",
    serviceFee: "Phí dịch vụ",
    total: "Tổng cộng",
  },
  EN: {
    clientInformation: "Client Information",
    person: "Person",
    fullName: "Full Name",
    phone: "Phone Number",
    fullNamePlaceholder: "Enter full name",
    phonePlaceholder: "Enter phone number",
    availableDate: "Available Date",
    availableDatePlaceholder: "Select available date",
    guestSize: "Guest Size",
    guestSizePlaceholder: "Select guest size",
    bookingNewDate: "Book New Date",
    bookingNewDatePlaceholder: "Select new date",
    bookingRemainSlots: "Remaining Slots",
    bookingRemainSlotsPlaceholder: "Select remaining slots",
    bookingSlots: "Booking Slots",
    bookingSlotsPlaceholder: "Select booking slots",
    serviceFee: "Service Fee",
    total: "Total",
  },
};
